theme: jekyll-theme-hacker

title: ephos # used in <title> tag & site header
author: Anders Spælling # used in a <meta> tag & /feed.xml
description: > # used in a <meta> tag & /feed.xml
  my description, where does it go?.
slogan: ❤❤❤❤❤❤❤❤❤ # used in site header, beside title
url: https://spaelling.github.io/CodeBeaver

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
